### ISSUE TITLE
setup.py installs test dir

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [facelessuser/pyspelling#104]
The line in setup.py to prevent installation of tests dirs does not seem to be working:
```
    author_email='Isaac.Muse@gmail.com',
    url='https://github.com/facelessuser/pyspelling',
    packages=find_packages(exclude=['tests', 'tools']),
    entry_points=entry_points,
    install_requires=get_requirements(),
```

Gentoo's package manager Portage always checks for these dirs before installing and it is not happy with pyspelling:

```
ERROR: dev-python/pyspelling-2.6.0::guru failed (install phase):
*   Package installs 'tests' package which is forbidden and likely a bug in the build system.
```

The following patch fixes this for me:
```
--- a/setup.py	2020-03-28 09:44:36.634469819 +0100
+++ b/setup.py_fix	2020-03-28 09:48:38.754477130 +0100
@@ -59,7 +59,7 @@
     author='Isaac Muse',
     author_email='Isaac.Muse@gmail.com',
     url='https://github.com/facelessuser/pyspelling',
-    packages=find_packages(exclude=['tests', 'tools']),
+    packages=find_packages(exclude=('tests*', 'tools*')),
     entry_points=entry_points,
     install_requires=get_requirements(),
     license='MIT License',
```

**Comment by facelessuser** [comment]
Yeah, I forgot that `tests` and `tools` only works if you have no nested test folders....It's kind of an unintuitive interface. One would think that if you excluded the top level `tests` that all modules under it would be excluded...and yet here we are...

Thanks for reporting!

**Comment by facelessuser** [comment]
Fixed in https://github.com/facelessuser/pyspelling/commit/8811d0be2991c6a1f2b3deda752a20c1d889bada

@gir-bot add T: bug, S: confirmed
@gir-bot lgtm
