### ISSUE TITLE
Support other spell checkers

### ISSUE THREAD

**Issue by tbm** [facelessuser/pyspelling#121]
What do you think of adding support for other spell checkers, such as [codespell](https://github.com/codespell-project/codespell/) and [anorack](https://github.com/jwilk/anorack/)?

**Comment by facelessuser** [comment]
It's certainly possible, but I'd have to think about whether I have the motivation to do so. It definitely adds more maintenance cost. I mainly went for the two well known alternatives. These were the ones I was most likely to use. Support for others would require me to learn their ins and outs and maintain all 4 moving forward.

I wrote pyspelling mainly to help me spellcheck my projects in CI, not necessarily to be the one stop spellchecker for any spellchecker. With that said, I'll at least consider it.

@gir-bot add T: feature, P: maybe
@gir-bot remove S: triage

**Comment by facelessuser** [comment]
Looking closer at the suggested spell checkers, these seem very specialized. They aren't nearly as general purpose as aspell and hunspell.

I have to be honest, if these were more general purpose spell checker alternatives, there would be a better argument. I'm not saying these don't have their place, but compared to hunspell and aspell which are more general purpose and support many different languages, these two spell checker's focus is much more narrow, I would even classify `anorack` as a niche spell checker.

I will most likely be passing on adding support for these two spell checkers.

**Comment by tbm** [comment]
Yeah, that's fair enough.  Feel free to close this ticket.

I wasn't sure how open you were to changing pyspelling into a framework into which all kind of spelling and maybe even grammar tools could be plugged.  I'm fine if you don't want to go that way.

**Comment by facelessuser** [comment]
Yeah, there is no technical limitation that prevents us from extending to other checkers (that I'm aware of). The existing spell checkers are already abstracted into separate classes. It could very well be extended to support more if desired. But you do have to dig into each spell checker and learn their quirks, setup sanity checks for each checker, and keep up to date on any and all as new versions come out and break prior expectations.

If we were able to create some kind of general purpose plugin type so people could plug in different checkers, I'd be more open to that, then I wouldn't have to directly support such checkers, just the framework. People could then create and maintain their own plugins for their favorite checker.

When we start to talk about grammar checkers (which honestly `anorack` seems more like a grammar checker), we may run into issues where it doesn't quite translate into the expected framework. For instance, does `anorack` use the idea of custom dictionaries or wordlists to ignore false positives? Maybe the user could just stub out those hooks if we had a framework or maybe augment it to better fit whatever checker they are using 🤷‍♂️.

Anyways, I may be more willing to look into creating a generalized plugin framework for the checker. Taking on the maintenance of everyone's favorite check is probably beyond what I am willing to do.

**Comment by tbm** [comment]
> For instance, does anorack use the idea of custom dictionaries or wordlists to ignore false positives?

No, it doesn't.

Anyway, I don't mind if you close this ticket.  It's really up to you if you want to provide more generic infrastructure or just focus on aspell/hunspell.

**Comment by facelessuser** [comment]
For now, I'll close it. If in the future there are enough requests, I may consider implementing some kind of a framework.

@gir-bot add S: wontfix

**Comment by tbm** [comment]
No problem.  Thanks for being so responsive!
