### ISSUE TITLE
Please allow .pyspelling.yaml config (.yaml, not .yml)

### ISSUE THREAD

**Issue by tbm** [facelessuser/pyspelling#122]
The [YAML FAQ](https://yaml.org/faq.html) says:

> Is there an official extension for YAML files?
>
> Please use ".yaml" when possible.

Please allow `.pyspelling.yaml`.

**Comment by facelessuser** [comment]
I do see they "prefer" `yaml`, but let's be honest, tons of people use `yml`. We do allow the user to specify a config if they want to use something different as well.

With that said, we can probably look for both `.pyspelling.yaml` and `.pyspelling.yml` moving forward.

@gir-bot add T: feature
@gir-bot remove S: triage

**Comment by tbm** [comment]
> With that said, we can probably look for both .pyspelling.yaml and .pyspelling.yml moving forward.

That's what I wanted to suggest, sorry for not being clear.
