### ISSUE TITLE
Cannot specify multiple source files on command line

### ISSUE THREAD

**Issue by miff2000** [facelessuser/pyspelling#132]
I am trying to get pyspelling to only scan changed (or new) files in a MR/PR. To do that, I've took the `sources` key out of my `pyspelling.yaml` file and I've specified multiple `--source` flags on the command line. I can see this _would_ work thanks to the flag being set to `append` here:

* <https://github.com/facelessuser/pyspelling/blob/fe3e88f/pyspelling/__main__.py#L20>

However, this bit of code stops me from doing that:

* https://github.com/facelessuser/pyspelling/blob/fe3e88f149a83ea620a0426861e745923845643d/pyspelling/__init__.py#L641-L643

If I comment that out, I can then get pyspelling to only scan the files I've specified. Similarly, if I don't specify files using the ``--source` flag, it 

Can you tell me what that bit of code is meant to do? Is the logic not quite right perhaps?

**Comment by facelessuser** [comment]
The `name` is the job in the spellcheck you want to run. For instance, in my config I have spellcheck for Python source comments and one for Documentation, etc. If from the command line, I specify `python`, I can specify all the patterns I like:

```
pyspelling -n python -s *.py -s *.whatever
```

Keep in mind, the `-s` overrides the current job's `source`.

If I run multiple jobs, it makes less sense to override them all with the same source:

```
pyspelling -n python -n mkdocs -s *.py *.html
```

So now I'm searching python source files and html source files for both jobs, but each job is configured to spellcheck very specific file types, the first being python source, the second HTML. But now I'm searching both file types for both jobs. That is why it is limited.

What you want to do is run pyspelling multiple times in this case:

```
pyspelling -n python -s *.py
pyspelling -n mkdocs -s *.html
```

Hopefully, that makes sense. If you need something else, we'll have to discuss it as while it might at first blush make sense, considering it further may prove that it is a bad idea, but maybe there is an approach I haven't thought about.

**Comment by facelessuser** [comment]
I wanted to check to make sure, and I do mention this in the documentation, but maybe I should also mention it in the `--help` output.

> If you've specified exactly one name via the name option, you can override that named task's source patterns with the source option. You can specify multiple source patterns if desired.

**Comment by miff2000** [comment]
Ah, that explains it! Thanks for the quick response and the help message update :)
