### ISSUE TITLE
Feature: doubly-bounded matching for the Context filter

### ISSUE THREAD

**Issue by gj** [facelessuser/pyspelling#136]
Hi! Thanks for the great package.

I think this `\Z` fallback pattern might be a bit too happy to swallow up everything from the `'open'` delimiter to the end of the file:

https://github.com/facelessuser/pyspelling/blob/435efc50add4e4d794e6c0c868083dbd995d831c/pyspelling/filters/context.py#L66

For example, here's a failing test case:

```diff
diff --git a/tests/filters/test_context.py b/tests/filters/test_context.py
index 571cf0e..31bab90 100644
--- a/tests/filters/test_context.py
+++ b/tests/filters/test_context.py
@@ -113,0 +114,15 @@ class TestContextChained(util.PluginTestCase):
+
+    def test_context_without_matching_close(self):
+        """Test context when 'close' pattern doesn't match and \\Z fallback is
+        used."""
+
+        bad_words = ["helo", "begn"]
+        good_words = ["yes", "word"]
+        template = self.dedent(
+            """
+            ```
+            {}
+            """
+        ).format("\n".join(bad_words + good_words))
+        self.mktemp("test.txt", template, "utf-8")
+        self.assert_spellcheck(".context.yml", bad_words)
```

Since there's no closing code fence (`` ``` ``), I would expect both `bad_words` to be marked as spelling errors. Unfortunately, the regex happily skips everything from the opening code fence to the end of the file.

**Comment by facelessuser** [comment]
@gj This is works currently as intended. You start an exclusion via some start pattern, you end the exclusion with some end pattern, in your case ` ``` ` is used for both opening and closing. So, you start an exclusion block, and it continues until it finds an end pattern or hits the end of the buffer. The regular expression is explicitly following this logic, so `\Z` is very purposefully there.

This is described in the first paragraph in the docs related to the context filter: https://facelessuser.github.io/pyspelling/filters/context/. Now, maybe it still isn't clear enough and leaves room for people to make certain assumptions, but this is definitely not a mistake, but intended behavior.

What you are requesting is something a bit different. You want it to only exclude if both the start and end patterns are found. This would be a feature request, not a bug. If implemented, it would probably be an option that a user could enable if desired.

@gir-bot remove S: triage
@gir-bot add T: feature, P: maybe

**Comment by gj** [comment]
@facelessuser thanks for the quick response and clarification!

**Comment by gj** [comment]
I managed to figure out a workaround so I don't have an immediate need for this feature. Would you like me to close the issue or leave it open?

**Comment by facelessuser** [comment]
If you'd like me to remember to look into this, then I'd leave it open as I'll forget if we close it 🙂.

**Comment by gj** [comment]
Forget away! 😄
