### ISSUE TITLE
support for passing filtered content to generic checkers

### ISSUE THREAD

**Issue by grahamgower** [facelessuser/pyspelling#143]
`pyspelling`'s strength seems to be it's ability to deal with many different inputs and filter them appropriately before giving the filtered content to aspell or hunspell. It would be awesome to also be able to pass this filtered content to other applications. This would make it reasonably easy for users to apply grammar checking, duplicate word checking, or custom regexes with perl one-liners.

**Comment by facelessuser** [comment]
I will be honest, while I can understand the desire for such a feature, it is beyond the scope of PySpelling. PySpelling was born out of my need to better filter content for spell checking. That was the whole motivation and goal of the project. PySpelling is streamlined for the purpose of showing misspelled words.

The request, though it sounds simplistic in nature, would require a non-trivial amount of work to accomplish.  We would probably have to better split handling of the input content and filtering from the spell checking classes. Generalize the output targets. Rework how the output is handled so it is not so specific to handling spelling output as grammar checkers probably require significantly more interesting context output.

Then comes bigger implications. How do you easily ignore some grammar failures? There is just a lot of complexity that would probably go into this, especially if we wanted to handle grammar. Maybe less so for double words, but there are cases where double words can be acceptable. How would we ignore specific cases of double words that are grammatically proper? This is all much more complex than providing a simple wordlist.

Additionally, I do maintain multiple projects and help out on other projects as well, so keeping the maintenance burden low helps keep me from burning out. The more complex a project, the larger the maintenance burden.

While I am uncertain if I would go through the effort to completely generalized the output targets, it is possible that maybe we could separate filtering and inputs from the spell checkers in such a way that someone could potentially reuse them and build a grammar frontend (or whatever) around it, using PySpelling as some kind of dependency. If we were to do anything, this is probably the most likely thing we'd consider.

I'd have to think about this and see how much effort this would be. If I were to agree to do this, it would be low priority as it does not directly enhance the existing features or add new features within the defined scope of the project.

**Comment by facelessuser** [comment]
Unfortunately, I don't think I'll be spending time on this endeavor. Currently, I'm going to keep the focus on spell checking.
