### ISSUE TITLE
reStructuredText support

### ISSUE THREAD

**Issue by treyhunner** [facelessuser/pyspelling#149]
I'm considering using pyspelling to spell-check a Sphinx powered website (which uses reStructuredText files). I'd love to see an extension for Sphinx/rST support.

**Comment by facelessuser** [comment]
Hi, thanks for your interest. With that said, I'd like to mention the extensions I currently support are based on things that I use or have a need for. The idea of an extension system is that others will implement what they need via 3rd party plugins. Doing things this way keeps maintenance manageable for me.

With that said, I'm not sure you need a Sphinx extension per see. If you are doing a website, is there a reason that you can't just build it as HTML and then run the spellchecker on that? That's personally what I do for my own documentation: https://github.com/facelessuser/pyspelling/blob/master/tox.ini#L20.

**Comment by treyhunner** [comment]
I appreciate such a prompt response! You're right that I could run pyspelling against the generated HTML. For the time being I've decided to use a Sphinx extension that checks spelling.

@facelessuser I fully expected a "you can write an extension for that" answer. Given that Sphinx has its own spell-checking extension, I think this issue may not be worth keeping open.

I'm happily using pyspelling to spell check about 400,000 words worth of markdown. Thanks for the great tool! 👍

**Comment by facelessuser** [comment]
Glad to hear you find it useful, even if not for rST stuff :).

If this was the only project I supported, or if I was actively using rST, I'd probably be more open to supporting it. Since I do support a good number of projects, I'm a bit picky on what I choose to tackle.
