### ISSUE TITLE
Unknown mode: "none"

### ISSUE THREAD

**Issue by Praecordi** [facelessuser/pyspelling#162]
I kept facing an error `Unknown mode: "none"` when trying to run through a txt file
I found this pull request https://github.com/facelessuser/pyspelling/pull/79, which gave me the idea to specifically put mode with an empty string to disable that.
So this:
```
aspell
  lang: en
  d: en_US
  mode:
```
fixed the issue for me. 

Any idea why this happened to me?

**Comment by facelessuser** [comment]
`null` is probably more appropriate in YAML

**Comment by facelessuser** [comment]
Hopefully this answered your question, if it didn't feel free to reopen.

**Comment by facelessuser** [comment]
I was looking at this recently as I am tweaking some things. By default, we set mode to `none`, per Aspell's documentation: 

```
none           mode to disable all filters
```

This is equivalent to `aspell --mode none`

If you are using an Aspell that does not support mode `none`, I'd like to know what version it is. Frankly, I think I dismissed this issue as you provided very little info. If this is still an issue, and you can provide detailed information, I'd be happy to take another look to at least understand what the issue may be.
