### ISSUE TITLE
If the configuration file is not present pyspelling checks nothing and reports success

### ISSUE THREAD

**Issue by timgates42** [facelessuser/pyspelling#80]
If the pyspelling.yml or other configuration file is removed accidentally, pyspelling does not warn or fail but instead checks nothing and reports

```
Spelling check passed :)
```

It might be worth failing as the lack of configuration file is a major problem.

**Comment by facelessuser** [comment]
I'm going to close this issue as it has now been resolved. Thinking about this more, it would probably be useful to also throw an error if no matrix entries are defined, or a specific name is specified, and it doesn't exist in the matrix, but I will most likely look into that as a separate issue. Thanks for the report!

**Comment by timgates42** [comment]
I had a go at the matrix https://github.com/facelessuser/pyspelling/pull/85 - let me know what you think if you want any changes - I'll have a look at some more cases too
